<?php
/**
 * EncryptionAlgorithm
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EncryptionAlgorithm Class Doc Comment
 *
 * @category Class
 * @description Specifies the encryption algorithm.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EncryptionAlgorithm
{
    /**
     * Possible values of this enum
     */
    const PDF_ENCRYPTION_NONE = 'PdfEncryptionNone';
    const PDF_ENCRYPTION40_BIT_RC4 = 'PdfEncryption40BitRC4';
    const PDF_ENCRYPTION128_BIT_RC4 = 'PdfEncryption128BitRC4';
    const PDF_ENCRYPTION128_BIT_AES = 'PdfEncryption128BitAES';
    const PDF_ENCRYPTION256_BIT_AES = 'PdfEncryption256BitAES';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PDF_ENCRYPTION_NONE,
            self::PDF_ENCRYPTION40_BIT_RC4,
            self::PDF_ENCRYPTION128_BIT_RC4,
            self::PDF_ENCRYPTION128_BIT_AES,
            self::PDF_ENCRYPTION256_BIT_AES,
        ];
    }
}


