<?php
/**
 * FreeTextAnnotationParameters
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * FreeTextAnnotationParameters Class Doc Comment
 *
 * @category Class
 * @description Represents information about the FreeText Annotation.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FreeTextAnnotationParameters implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'FreeTextAnnotationParameters';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'annotation_layout' => '\OpenAPI\Client\Model\DrawableContentLayoutParameters',
        'text_parameters' => '\OpenAPI\Client\Model\PdfTextParameters',
        'title' => 'string',
        'subject' => 'string',
        'show_border' => 'bool',
        'color' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'annotation_layout' => null,
        'text_parameters' => null,
        'title' => null,
        'subject' => null,
        'show_border' => null,
        'color' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'annotation_layout' => 'AnnotationLayout',
        'text_parameters' => 'TextParameters',
        'title' => 'Title',
        'subject' => 'Subject',
        'show_border' => 'ShowBorder',
        'color' => 'Color'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'annotation_layout' => 'setAnnotationLayout',
        'text_parameters' => 'setTextParameters',
        'title' => 'setTitle',
        'subject' => 'setSubject',
        'show_border' => 'setShowBorder',
        'color' => 'setColor'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'annotation_layout' => 'getAnnotationLayout',
        'text_parameters' => 'getTextParameters',
        'title' => 'getTitle',
        'subject' => 'getSubject',
        'show_border' => 'getShowBorder',
        'color' => 'getColor'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['annotation_layout'] = isset($data['annotation_layout']) ? $data['annotation_layout'] : null;
        $this->container['text_parameters'] = isset($data['text_parameters']) ? $data['text_parameters'] : null;
        $this->container['title'] = isset($data['title']) ? $data['title'] : null;
        $this->container['subject'] = isset($data['subject']) ? $data['subject'] : null;
        $this->container['show_border'] = isset($data['show_border']) ? $data['show_border'] : null;
        $this->container['color'] = isset($data['color']) ? $data['color'] : 'red';
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['annotation_layout'] === null) {
            $invalidProperties[] = "'annotation_layout' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets annotation_layout
     *
     * @return \OpenAPI\Client\Model\DrawableContentLayoutParameters
     */
    public function getAnnotationLayout()
    {
        return $this->container['annotation_layout'];
    }

    /**
     * Sets annotation_layout
     *
     * @param \OpenAPI\Client\Model\DrawableContentLayoutParameters $annotation_layout annotation_layout
     *
     * @return $this
     */
    public function setAnnotationLayout($annotation_layout)
    {
        $this->container['annotation_layout'] = $annotation_layout;

        return $this;
    }

    /**
     * Gets text_parameters
     *
     * @return \OpenAPI\Client\Model\PdfTextParameters|null
     */
    public function getTextParameters()
    {
        return $this->container['text_parameters'];
    }

    /**
     * Sets text_parameters
     *
     * @param \OpenAPI\Client\Model\PdfTextParameters|null $text_parameters text_parameters
     *
     * @return $this
     */
    public function setTextParameters($text_parameters)
    {
        $this->container['text_parameters'] = $text_parameters;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title Specifies the title of the annotation, if any.
     *
     * @return $this
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return string|null
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string|null $subject Specify the subject of the annotation, if any.
     *
     * @return $this
     */
    public function setSubject($subject)
    {
        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets show_border
     *
     * @return bool|null
     */
    public function getShowBorder()
    {
        return $this->container['show_border'];
    }

    /**
     * Sets show_border
     *
     * @param bool|null $show_border Specifies if the annotation border shall be drawn.
     *
     * @return $this
     */
    public function setShowBorder($show_border)
    {
        $this->container['show_border'] = $show_border;

        return $this;
    }

    /**
     * Gets color
     *
     * @return string|null
     */
    public function getColor()
    {
        return $this->container['color'];
    }

    /**
     * Sets color
     *
     * @param string|null $color Specifies the color of the annotation, using the color name (ie: \"red\") or its RGBa code (ie: \"rgba(255,0,0,1)\").
     *
     * @return $this
     */
    public function setColor($color)
    {
        $this->container['color'] = $color;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


