<?php
/**
 * ImageAdjustParameters
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ImageAdjustParameters Class Doc Comment
 *
 * @category Class
 * @description Represents the parameters for an image adjustment action.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ImageAdjustParameters implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ImageAdjustParameters';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'file_id' => 'string',
        'page_range' => 'string',
        'roi_left' => 'int',
        'roi_top' => 'int',
        'roi_width' => 'int',
        'roi_height' => 'int',
        'gamma_correction' => 'int',
        'brightness' => 'int',
        'contrast' => 'int',
        'saturation' => 'int',
        'auto_contrast_enhancement' => 'bool',
        'contrast_histogram_stretch' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'file_id' => null,
        'page_range' => null,
        'roi_left' => 'int32',
        'roi_top' => 'int32',
        'roi_width' => 'int32',
        'roi_height' => 'int32',
        'gamma_correction' => 'int32',
        'brightness' => 'int32',
        'contrast' => 'int32',
        'saturation' => 'int32',
        'auto_contrast_enhancement' => null,
        'contrast_histogram_stretch' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'file_id' => 'FileId',
        'page_range' => 'PageRange',
        'roi_left' => 'RoiLeft',
        'roi_top' => 'RoiTop',
        'roi_width' => 'RoiWidth',
        'roi_height' => 'RoiHeight',
        'gamma_correction' => 'GammaCorrection',
        'brightness' => 'Brightness',
        'contrast' => 'Contrast',
        'saturation' => 'Saturation',
        'auto_contrast_enhancement' => 'AutoContrastEnhancement',
        'contrast_histogram_stretch' => 'ContrastHistogramStretch'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'file_id' => 'setFileId',
        'page_range' => 'setPageRange',
        'roi_left' => 'setRoiLeft',
        'roi_top' => 'setRoiTop',
        'roi_width' => 'setRoiWidth',
        'roi_height' => 'setRoiHeight',
        'gamma_correction' => 'setGammaCorrection',
        'brightness' => 'setBrightness',
        'contrast' => 'setContrast',
        'saturation' => 'setSaturation',
        'auto_contrast_enhancement' => 'setAutoContrastEnhancement',
        'contrast_histogram_stretch' => 'setContrastHistogramStretch'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'file_id' => 'getFileId',
        'page_range' => 'getPageRange',
        'roi_left' => 'getRoiLeft',
        'roi_top' => 'getRoiTop',
        'roi_width' => 'getRoiWidth',
        'roi_height' => 'getRoiHeight',
        'gamma_correction' => 'getGammaCorrection',
        'brightness' => 'getBrightness',
        'contrast' => 'getContrast',
        'saturation' => 'getSaturation',
        'auto_contrast_enhancement' => 'getAutoContrastEnhancement',
        'contrast_histogram_stretch' => 'getContrastHistogramStretch'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['file_id'] = isset($data['file_id']) ? $data['file_id'] : null;
        $this->container['page_range'] = isset($data['page_range']) ? $data['page_range'] : null;
        $this->container['roi_left'] = isset($data['roi_left']) ? $data['roi_left'] : 0;
        $this->container['roi_top'] = isset($data['roi_top']) ? $data['roi_top'] : 0;
        $this->container['roi_width'] = isset($data['roi_width']) ? $data['roi_width'] : 0;
        $this->container['roi_height'] = isset($data['roi_height']) ? $data['roi_height'] : 0;
        $this->container['gamma_correction'] = isset($data['gamma_correction']) ? $data['gamma_correction'] : 0;
        $this->container['brightness'] = isset($data['brightness']) ? $data['brightness'] : 0;
        $this->container['contrast'] = isset($data['contrast']) ? $data['contrast'] : 0;
        $this->container['saturation'] = isset($data['saturation']) ? $data['saturation'] : 0;
        $this->container['auto_contrast_enhancement'] = isset($data['auto_contrast_enhancement']) ? $data['auto_contrast_enhancement'] : false;
        $this->container['contrast_histogram_stretch'] = isset($data['contrast_histogram_stretch']) ? $data['contrast_histogram_stretch'] : false;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['file_id'] === null) {
            $invalidProperties[] = "'file_id' can't be null";
        }
        if ($this->container['page_range'] === null) {
            $invalidProperties[] = "'page_range' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets file_id
     *
     * @return string
     */
    public function getFileId()
    {
        return $this->container['file_id'];
    }

    /**
     * Sets file_id
     *
     * @param string $file_id The identifier of the previously uploaded file to be processed.
     *
     * @return $this
     */
    public function setFileId($file_id)
    {
        $this->container['file_id'] = $file_id;

        return $this;
    }

    /**
     * Gets page_range
     *
     * @return string
     */
    public function getPageRange()
    {
        return $this->container['page_range'];
    }

    /**
     * Sets page_range
     *
     * @param string $page_range Specifies the number of the page, or the range of pages to adjust.
     *
     * @return $this
     */
    public function setPageRange($page_range)
    {
        $this->container['page_range'] = $page_range;

        return $this;
    }

    /**
     * Gets roi_left
     *
     * @return int|null
     */
    public function getRoiLeft()
    {
        return $this->container['roi_left'];
    }

    /**
     * Sets roi_left
     *
     * @param int|null $roi_left Specifies the left coordinate, in pixel, of the region to process.
     *
     * @return $this
     */
    public function setRoiLeft($roi_left)
    {
        $this->container['roi_left'] = $roi_left;

        return $this;
    }

    /**
     * Gets roi_top
     *
     * @return int|null
     */
    public function getRoiTop()
    {
        return $this->container['roi_top'];
    }

    /**
     * Sets roi_top
     *
     * @param int|null $roi_top Specifies the top coordinate, in pixel, of the region to process.
     *
     * @return $this
     */
    public function setRoiTop($roi_top)
    {
        $this->container['roi_top'] = $roi_top;

        return $this;
    }

    /**
     * Gets roi_width
     *
     * @return int|null
     */
    public function getRoiWidth()
    {
        return $this->container['roi_width'];
    }

    /**
     * Sets roi_width
     *
     * @param int|null $roi_width Specifies the width, in pixel, of the region to process. 0 causes the entire image to be processed.
     *
     * @return $this
     */
    public function setRoiWidth($roi_width)
    {
        $this->container['roi_width'] = $roi_width;

        return $this;
    }

    /**
     * Gets roi_height
     *
     * @return int|null
     */
    public function getRoiHeight()
    {
        return $this->container['roi_height'];
    }

    /**
     * Sets roi_height
     *
     * @param int|null $roi_height Specifies the height, in pixel, of the region to process. 0 causes the entire image to be processed.
     *
     * @return $this
     */
    public function setRoiHeight($roi_height)
    {
        $this->container['roi_height'] = $roi_height;

        return $this;
    }

    /**
     * Gets gamma_correction
     *
     * @return int|null
     */
    public function getGammaCorrection()
    {
        return $this->container['gamma_correction'];
    }

    /**
     * Sets gamma_correction
     *
     * @param int|null $gamma_correction Specifies the gamma correction parameter.
     *
     * @return $this
     */
    public function setGammaCorrection($gamma_correction)
    {
        $this->container['gamma_correction'] = $gamma_correction;

        return $this;
    }

    /**
     * Gets brightness
     *
     * @return int|null
     */
    public function getBrightness()
    {
        return $this->container['brightness'];
    }

    /**
     * Sets brightness
     *
     * @param int|null $brightness Specifies the brightness parameter.
     *
     * @return $this
     */
    public function setBrightness($brightness)
    {
        $this->container['brightness'] = $brightness;

        return $this;
    }

    /**
     * Gets contrast
     *
     * @return int|null
     */
    public function getContrast()
    {
        return $this->container['contrast'];
    }

    /**
     * Sets contrast
     *
     * @param int|null $contrast Specifies the contrast parameter.
     *
     * @return $this
     */
    public function setContrast($contrast)
    {
        $this->container['contrast'] = $contrast;

        return $this;
    }

    /**
     * Gets saturation
     *
     * @return int|null
     */
    public function getSaturation()
    {
        return $this->container['saturation'];
    }

    /**
     * Sets saturation
     *
     * @param int|null $saturation Specifies the saturation parameter.
     *
     * @return $this
     */
    public function setSaturation($saturation)
    {
        $this->container['saturation'] = $saturation;

        return $this;
    }

    /**
     * Gets auto_contrast_enhancement
     *
     * @return bool|null
     */
    public function getAutoContrastEnhancement()
    {
        return $this->container['auto_contrast_enhancement'];
    }

    /**
     * Sets auto_contrast_enhancement
     *
     * @param bool|null $auto_contrast_enhancement Specifies whether the contrast shall be automatically enhanced.
     *
     * @return $this
     */
    public function setAutoContrastEnhancement($auto_contrast_enhancement)
    {
        $this->container['auto_contrast_enhancement'] = $auto_contrast_enhancement;

        return $this;
    }

    /**
     * Gets contrast_histogram_stretch
     *
     * @return bool|null
     */
    public function getContrastHistogramStretch()
    {
        return $this->container['contrast_histogram_stretch'];
    }

    /**
     * Sets contrast_histogram_stretch
     *
     * @param bool|null $contrast_histogram_stretch Specifies whether a contrast histogram stretch filter shall be performed.
     *
     * @return $this
     */
    public function setContrastHistogramStretch($contrast_histogram_stretch)
    {
        $this->container['contrast_histogram_stretch'] = $contrast_histogram_stretch;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


