<?php
/**
 * ImageMICRParameters
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ImageMICRParameters Class Doc Comment
 *
 * @category Class
 * @description Represents the parameters for a MICR action.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ImageMICRParameters implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ImageMICRParameters';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'file_id' => 'string',
        'page_range' => 'string',
        'font' => '\OpenAPI\Client\Model\MicrFont',
        'context' => '\OpenAPI\Client\Model\MicrContext',
        'white_list' => 'string',
        'roi_left' => 'int',
        'roi_top' => 'int',
        'roi_width' => 'int',
        'roi_height' => 'int',
        'expected_symbols_count' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'file_id' => null,
        'page_range' => null,
        'font' => null,
        'context' => null,
        'white_list' => null,
        'roi_left' => 'int32',
        'roi_top' => 'int32',
        'roi_width' => 'int32',
        'roi_height' => 'int32',
        'expected_symbols_count' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'file_id' => 'FileId',
        'page_range' => 'PageRange',
        'font' => 'Font',
        'context' => 'Context',
        'white_list' => 'WhiteList',
        'roi_left' => 'RoiLeft',
        'roi_top' => 'RoiTop',
        'roi_width' => 'RoiWidth',
        'roi_height' => 'RoiHeight',
        'expected_symbols_count' => 'ExpectedSymbolsCount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'file_id' => 'setFileId',
        'page_range' => 'setPageRange',
        'font' => 'setFont',
        'context' => 'setContext',
        'white_list' => 'setWhiteList',
        'roi_left' => 'setRoiLeft',
        'roi_top' => 'setRoiTop',
        'roi_width' => 'setRoiWidth',
        'roi_height' => 'setRoiHeight',
        'expected_symbols_count' => 'setExpectedSymbolsCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'file_id' => 'getFileId',
        'page_range' => 'getPageRange',
        'font' => 'getFont',
        'context' => 'getContext',
        'white_list' => 'getWhiteList',
        'roi_left' => 'getRoiLeft',
        'roi_top' => 'getRoiTop',
        'roi_width' => 'getRoiWidth',
        'roi_height' => 'getRoiHeight',
        'expected_symbols_count' => 'getExpectedSymbolsCount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['file_id'] = isset($data['file_id']) ? $data['file_id'] : null;
        $this->container['page_range'] = isset($data['page_range']) ? $data['page_range'] : null;
        $this->container['font'] = isset($data['font']) ? $data['font'] : null;
        $this->container['context'] = isset($data['context']) ? $data['context'] : null;
        $this->container['white_list'] = isset($data['white_list']) ? $data['white_list'] : '';
        $this->container['roi_left'] = isset($data['roi_left']) ? $data['roi_left'] : 0;
        $this->container['roi_top'] = isset($data['roi_top']) ? $data['roi_top'] : 0;
        $this->container['roi_width'] = isset($data['roi_width']) ? $data['roi_width'] : 0;
        $this->container['roi_height'] = isset($data['roi_height']) ? $data['roi_height'] : 0;
        $this->container['expected_symbols_count'] = isset($data['expected_symbols_count']) ? $data['expected_symbols_count'] : 0;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['file_id'] === null) {
            $invalidProperties[] = "'file_id' can't be null";
        }
        if ($this->container['page_range'] === null) {
            $invalidProperties[] = "'page_range' can't be null";
        }
        if ($this->container['font'] === null) {
            $invalidProperties[] = "'font' can't be null";
        }
        if ($this->container['context'] === null) {
            $invalidProperties[] = "'context' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets file_id
     *
     * @return string
     */
    public function getFileId()
    {
        return $this->container['file_id'];
    }

    /**
     * Sets file_id
     *
     * @param string $file_id The identifier of the previously uploaded file to be processed.
     *
     * @return $this
     */
    public function setFileId($file_id)
    {
        $this->container['file_id'] = $file_id;

        return $this;
    }

    /**
     * Gets page_range
     *
     * @return string
     */
    public function getPageRange()
    {
        return $this->container['page_range'];
    }

    /**
     * Sets page_range
     *
     * @param string $page_range Specifies the page or the range of page to be processed.
     *
     * @return $this
     */
    public function setPageRange($page_range)
    {
        $this->container['page_range'] = $page_range;

        return $this;
    }

    /**
     * Gets font
     *
     * @return \OpenAPI\Client\Model\MicrFont
     */
    public function getFont()
    {
        return $this->container['font'];
    }

    /**
     * Sets font
     *
     * @param \OpenAPI\Client\Model\MicrFont $font font
     *
     * @return $this
     */
    public function setFont($font)
    {
        $this->container['font'] = $font;

        return $this;
    }

    /**
     * Gets context
     *
     * @return \OpenAPI\Client\Model\MicrContext
     */
    public function getContext()
    {
        return $this->container['context'];
    }

    /**
     * Sets context
     *
     * @param \OpenAPI\Client\Model\MicrContext $context context
     *
     * @return $this
     */
    public function setContext($context)
    {
        $this->container['context'] = $context;

        return $this;
    }

    /**
     * Gets white_list
     *
     * @return string|null
     */
    public function getWhiteList()
    {
        return $this->container['white_list'];
    }

    /**
     * Sets white_list
     *
     * @param string|null $white_list Specifies the characters to be ignored by the recognition process.
     *
     * @return $this
     */
    public function setWhiteList($white_list)
    {
        $this->container['white_list'] = $white_list;

        return $this;
    }

    /**
     * Gets roi_left
     *
     * @return int|null
     */
    public function getRoiLeft()
    {
        return $this->container['roi_left'];
    }

    /**
     * Sets roi_left
     *
     * @param int|null $roi_left Specifies the left coordinate, in pixel, of the region to process.
     *
     * @return $this
     */
    public function setRoiLeft($roi_left)
    {
        $this->container['roi_left'] = $roi_left;

        return $this;
    }

    /**
     * Gets roi_top
     *
     * @return int|null
     */
    public function getRoiTop()
    {
        return $this->container['roi_top'];
    }

    /**
     * Sets roi_top
     *
     * @param int|null $roi_top Specifies the top coordinate, in pixel, of the region to process.
     *
     * @return $this
     */
    public function setRoiTop($roi_top)
    {
        $this->container['roi_top'] = $roi_top;

        return $this;
    }

    /**
     * Gets roi_width
     *
     * @return int|null
     */
    public function getRoiWidth()
    {
        return $this->container['roi_width'];
    }

    /**
     * Sets roi_width
     *
     * @param int|null $roi_width Specifies the width, in pixel, of the region to process. 0 causes the entire image to be processed.
     *
     * @return $this
     */
    public function setRoiWidth($roi_width)
    {
        $this->container['roi_width'] = $roi_width;

        return $this;
    }

    /**
     * Gets roi_height
     *
     * @return int|null
     */
    public function getRoiHeight()
    {
        return $this->container['roi_height'];
    }

    /**
     * Sets roi_height
     *
     * @param int|null $roi_height Specifies the height, in pixel, of the region to process. 0 causes the entire image to be processed.
     *
     * @return $this
     */
    public function setRoiHeight($roi_height)
    {
        $this->container['roi_height'] = $roi_height;

        return $this;
    }

    /**
     * Gets expected_symbols_count
     *
     * @return int|null
     */
    public function getExpectedSymbolsCount()
    {
        return $this->container['expected_symbols_count'];
    }

    /**
     * Sets expected_symbols_count
     *
     * @param int|null $expected_symbols_count Specifies the number of symbols expected to be detected, use 0 if unknown.
     *
     * @return $this
     */
    public function setExpectedSymbolsCount($expected_symbols_count)
    {
        $this->container['expected_symbols_count'] = $expected_symbols_count;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


