<?php
/**
 * LineAnnotationParameters
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * LineAnnotationParameters Class Doc Comment
 *
 * @category Class
 * @description Represents information about the Line Annotation.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LineAnnotationParameters implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'LineAnnotationParameters';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'line_start_x' => 'float',
        'line_start_y' => 'float',
        'line_end_x' => 'float',
        'line_end_y' => 'float',
        'title' => 'string',
        'content' => 'string',
        'line_start_style' => '\OpenAPI\Client\Model\LineAnnotationEndingStyle',
        'line_end_style' => '\OpenAPI\Client\Model\LineAnnotationEndingStyle',
        'show_content' => 'bool',
        'line_width' => '\OpenAPI\Client\Model\ContentSize',
        'absolute_annotation_line_width' => 'float',
        'color' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'line_start_x' => 'float',
        'line_start_y' => 'float',
        'line_end_x' => 'float',
        'line_end_y' => 'float',
        'title' => null,
        'content' => null,
        'line_start_style' => null,
        'line_end_style' => null,
        'show_content' => null,
        'line_width' => null,
        'absolute_annotation_line_width' => 'float',
        'color' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'line_start_x' => 'LineStartX',
        'line_start_y' => 'LineStartY',
        'line_end_x' => 'LineEndX',
        'line_end_y' => 'LineEndY',
        'title' => 'Title',
        'content' => 'Content',
        'line_start_style' => 'LineStartStyle',
        'line_end_style' => 'LineEndStyle',
        'show_content' => 'ShowContent',
        'line_width' => 'LineWidth',
        'absolute_annotation_line_width' => 'AbsoluteAnnotationLineWidth',
        'color' => 'Color'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'line_start_x' => 'setLineStartX',
        'line_start_y' => 'setLineStartY',
        'line_end_x' => 'setLineEndX',
        'line_end_y' => 'setLineEndY',
        'title' => 'setTitle',
        'content' => 'setContent',
        'line_start_style' => 'setLineStartStyle',
        'line_end_style' => 'setLineEndStyle',
        'show_content' => 'setShowContent',
        'line_width' => 'setLineWidth',
        'absolute_annotation_line_width' => 'setAbsoluteAnnotationLineWidth',
        'color' => 'setColor'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'line_start_x' => 'getLineStartX',
        'line_start_y' => 'getLineStartY',
        'line_end_x' => 'getLineEndX',
        'line_end_y' => 'getLineEndY',
        'title' => 'getTitle',
        'content' => 'getContent',
        'line_start_style' => 'getLineStartStyle',
        'line_end_style' => 'getLineEndStyle',
        'show_content' => 'getShowContent',
        'line_width' => 'getLineWidth',
        'absolute_annotation_line_width' => 'getAbsoluteAnnotationLineWidth',
        'color' => 'getColor'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['line_start_x'] = isset($data['line_start_x']) ? $data['line_start_x'] : null;
        $this->container['line_start_y'] = isset($data['line_start_y']) ? $data['line_start_y'] : null;
        $this->container['line_end_x'] = isset($data['line_end_x']) ? $data['line_end_x'] : null;
        $this->container['line_end_y'] = isset($data['line_end_y']) ? $data['line_end_y'] : null;
        $this->container['title'] = isset($data['title']) ? $data['title'] : null;
        $this->container['content'] = isset($data['content']) ? $data['content'] : null;
        $this->container['line_start_style'] = isset($data['line_start_style']) ? $data['line_start_style'] : null;
        $this->container['line_end_style'] = isset($data['line_end_style']) ? $data['line_end_style'] : null;
        $this->container['show_content'] = isset($data['show_content']) ? $data['show_content'] : null;
        $this->container['line_width'] = isset($data['line_width']) ? $data['line_width'] : null;
        $this->container['absolute_annotation_line_width'] = isset($data['absolute_annotation_line_width']) ? $data['absolute_annotation_line_width'] : null;
        $this->container['color'] = isset($data['color']) ? $data['color'] : 'red';
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets line_start_x
     *
     * @return float|null
     */
    public function getLineStartX()
    {
        return $this->container['line_start_x'];
    }

    /**
     * Sets line_start_x
     *
     * @param float|null $line_start_x Specifies if the horizontal coordinate of line annotation start point.
     *
     * @return $this
     */
    public function setLineStartX($line_start_x)
    {
        $this->container['line_start_x'] = $line_start_x;

        return $this;
    }

    /**
     * Gets line_start_y
     *
     * @return float|null
     */
    public function getLineStartY()
    {
        return $this->container['line_start_y'];
    }

    /**
     * Sets line_start_y
     *
     * @param float|null $line_start_y Specifies if the vertical coordinate of line annotation start point.
     *
     * @return $this
     */
    public function setLineStartY($line_start_y)
    {
        $this->container['line_start_y'] = $line_start_y;

        return $this;
    }

    /**
     * Gets line_end_x
     *
     * @return float|null
     */
    public function getLineEndX()
    {
        return $this->container['line_end_x'];
    }

    /**
     * Sets line_end_x
     *
     * @param float|null $line_end_x Specifies if the horizontal coordinate of line annotation end point.
     *
     * @return $this
     */
    public function setLineEndX($line_end_x)
    {
        $this->container['line_end_x'] = $line_end_x;

        return $this;
    }

    /**
     * Gets line_end_y
     *
     * @return float|null
     */
    public function getLineEndY()
    {
        return $this->container['line_end_y'];
    }

    /**
     * Sets line_end_y
     *
     * @param float|null $line_end_y Specifies if the vertical coordinate of line annotation end point.
     *
     * @return $this
     */
    public function setLineEndY($line_end_y)
    {
        $this->container['line_end_y'] = $line_end_y;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title Specifies the title of the annotation, if any.
     *
     * @return $this
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets content
     *
     * @return string|null
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     *
     * @param string|null $content Specify the content of the annotation, if any.
     *
     * @return $this
     */
    public function setContent($content)
    {
        $this->container['content'] = $content;

        return $this;
    }

    /**
     * Gets line_start_style
     *
     * @return \OpenAPI\Client\Model\LineAnnotationEndingStyle|null
     */
    public function getLineStartStyle()
    {
        return $this->container['line_start_style'];
    }

    /**
     * Sets line_start_style
     *
     * @param \OpenAPI\Client\Model\LineAnnotationEndingStyle|null $line_start_style line_start_style
     *
     * @return $this
     */
    public function setLineStartStyle($line_start_style)
    {
        $this->container['line_start_style'] = $line_start_style;

        return $this;
    }

    /**
     * Gets line_end_style
     *
     * @return \OpenAPI\Client\Model\LineAnnotationEndingStyle|null
     */
    public function getLineEndStyle()
    {
        return $this->container['line_end_style'];
    }

    /**
     * Sets line_end_style
     *
     * @param \OpenAPI\Client\Model\LineAnnotationEndingStyle|null $line_end_style line_end_style
     *
     * @return $this
     */
    public function setLineEndStyle($line_end_style)
    {
        $this->container['line_end_style'] = $line_end_style;

        return $this;
    }

    /**
     * Gets show_content
     *
     * @return bool|null
     */
    public function getShowContent()
    {
        return $this->container['show_content'];
    }

    /**
     * Sets show_content
     *
     * @param bool|null $show_content Specifies if the popup of annotation shall be opened by default.
     *
     * @return $this
     */
    public function setShowContent($show_content)
    {
        $this->container['show_content'] = $show_content;

        return $this;
    }

    /**
     * Gets line_width
     *
     * @return \OpenAPI\Client\Model\ContentSize|null
     */
    public function getLineWidth()
    {
        return $this->container['line_width'];
    }

    /**
     * Sets line_width
     *
     * @param \OpenAPI\Client\Model\ContentSize|null $line_width line_width
     *
     * @return $this
     */
    public function setLineWidth($line_width)
    {
        $this->container['line_width'] = $line_width;

        return $this;
    }

    /**
     * Gets absolute_annotation_line_width
     *
     * @return float|null
     */
    public function getAbsoluteAnnotationLineWidth()
    {
        return $this->container['absolute_annotation_line_width'];
    }

    /**
     * Sets absolute_annotation_line_width
     *
     * @param float|null $absolute_annotation_line_width Specifies the absolute line width of the annotation, in points.
     *
     * @return $this
     */
    public function setAbsoluteAnnotationLineWidth($absolute_annotation_line_width)
    {
        $this->container['absolute_annotation_line_width'] = $absolute_annotation_line_width;

        return $this;
    }

    /**
     * Gets color
     *
     * @return string|null
     */
    public function getColor()
    {
        return $this->container['color'];
    }

    /**
     * Sets color
     *
     * @param string|null $color Specifies the color of the annotation, using the color name (ie: \"red\") or its RGBa code (ie: \"rgba(255,0,0,1)\").
     *
     * @return $this
     */
    public function setColor($color)
    {
        $this->container['color'] = $color;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


