<?php
/**
 * PageViewMode
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PageViewMode Class Doc Comment
 *
 * @category Class
 * @description Defines how the pages are displayed on the screen.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PageViewMode
{
    /**
     * Possible values of this enum
     */
    const SINGLE_PAGE_VIEW = 'SinglePageView';
    const MULTIPLE_PAGES_VIEW = 'MultiplePagesView';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SINGLE_PAGE_VIEW,
            self::MULTIPLE_PAGES_VIEW,
        ];
    }
}


