<?php
/**
 * PassportPDFStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PassportPDFStatus Class Doc Comment
 *
 * @category Class
 * @description Specifies a PassportPDF status.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PassportPDFStatus
{
    /**
     * Possible values of this enum
     */
    const OK = 'OK';
    const ACTION_TIMED_OUT = 'ActionTimedOut';
    const EMPTY_PARAMETER = 'EmptyParameter';
    const INVALID_API_KEY = 'InvalidAPIKey';
    const NOT_ENOUGH_TOKENS = 'NotEnoughTokens';
    const GENERIC_ERROR = 'GenericError';
    const INVALID_PARAMETER = 'InvalidParameter';
    const INVALID_COLOR = 'InvalidColor';
    const OUT_OF_MEMORY = 'OutOfMemory';
    const NOT_IMPLEMENTED = 'NotImplemented';
    const FILE_NOT_FOUND = 'FileNotFound';
    const ACCESS_DENIED = 'AccessDenied';
    const CAN_NOT_IMPORT_FILE_TO_PDF = 'CanNotImportFileToPDF';
    const PDF_CAN_NOT_BE_DECRYPTED = 'PdfCanNotBeDecrypted';
    const PDF_OPERATION_NOT_ALLOWED = 'PdfOperationNotAllowed';
    const PDF_CAN_NOT_OPEN_FILE = 'PdfCanNotOpenFile';
    const PDF_CAN_NOT_SAVE_FILE = 'PdfCanNotSaveFile';
    const CAN_NOT_CREATE_FILE = 'CanNotCreateFile';
    const NO_DOCUMENT_PROVIDED = 'NoDocumentProvided';
    const CAN_NOT_REMOVE_PAGE = 'CanNotRemovePage';
    const CAN_NOT_SWAP_PAGES = 'CanNotSwapPages';
    const CAN_NOT_MOVE_PAGE = 'CanNotMovePage';
    const CAN_NOT_ROTATE_PAGE = 'CanNotRotatePage';
    const CAN_NOT_FLIP_PAGE = 'CanNotFlipPage';
    const INVALID_PAGE_RANGE = 'InvalidPageRange';
    const CAN_NOT_REDUCE_PDF = 'CanNotReducePDF';
    const CAN_NOT_AUTO_DESKEW = 'CanNotAutoDeskew';
    const CAN_NOT_SPLIT = 'CanNotSplit';
    const CAN_NOT_SAVE_AS_JPEG = 'CanNotSaveAsJPEG';
    const CAN_NOT_DIGI_SIGN = 'CanNotDigiSign';
    const CAN_NOT_PROTECT = 'CanNotProtect';
    const CAN_NOT_CONVERT_TO_PDFA = 'CanNotConvertToPDFA';
    const CAN_NOT_ANNOTATE = 'CanNotAnnotate';
    const CAN_NOT_CLEAR_PAGE = 'CanNotClearPage';
    const CAN_NOT_MERGE = 'CanNotMerge';
    const CAN_NOT_GET_PAGE_THUMBNAIL = 'CanNotGetPageThumbnail';
    const CAN_NOT_GET_DOCUMENT_PREVIEW = 'CanNotGetDocumentPreview';
    const CAN_NOT_REMOVE_PAGE_FORM_FIELDS = 'CanNotRemovePageFormFields';
    const CAN_NOT_INSERT_IMAGE = 'CanNotInsertImage';
    const CAN_NOT_DRAW_IMAGE = 'CanNotDrawImage';
    const CAN_NOT_INSERT_PAGE_NUMBER = 'CanNotInsertPageNumber';
    const CAN_NOT_INSERT_TEXT = 'CanNotInsertText';
    const CAN_NOT_READ_BARCODE = 'CanNotReadBarcode';
    const CAN_NOT_FLATTEN = 'CanNotFlatten';
    const CAN_NOT_EXPORT_MORE_THAN2_GIGABYTE_FILE = 'CanNotExportMoreThan2GigabyteFile';
    const CAN_NOT_OPEN_SESSION = 'CanNotOpenSession';
    const UNKNOWN_OR_EXPIRED_SESSION = 'UnknownOrExpiredSession';
    const CAN_NOT_SAVE_FILE = 'CanNotSaveFile';
    const CAN_NOT_REPAIR_PDF = 'CanNotRepairPDF';
    const UNSUPPORTED_IMAGE_FORMAT = 'UnsupportedImageFormat';
    const CAN_NOT_OCR = 'CanNotOCR';
    const CAN_NOT_OPEN_IMAGE = 'CanNotOpenImage';
    const CAN_NOT_SAVE_AS_PNG = 'CanNotSaveAsPNG';
    const CAN_NOT_SAVE_AS_TIFF = 'CanNotSaveAsTIFF';
    const CAN_NOT_SAVE_AS_TIFF_MULTIPAGE = 'CanNotSaveAsTIFFMultipage';
    const CAN_NOT_SET_INFO = 'CanNotSetInfo';
    const CAN_NOT_SET_PAGE_BOX = 'CanNotSetPageBox';
    const CAN_NOT_EXTRACT_PAGE = 'CanNotExtractPage';
    const CAN_NOT_INSERT_NEW_PAGE = 'CanNotInsertNewPage';
    const CAN_NOT_CLONE_PAGE = 'CanNotClonePage';
    const CAN_NOT_SET_INITIAL_VIEW = 'CanNotSetInitialView';
    const CAN_NOT_ADJUST = 'CanNotAdjust';
    const CAN_NOT_RESIZE = 'CanNotResize';
    const CAN_NOT_FILTER = 'CanNotFilter';
    const CAN_NOT_CLEANUP_DOCUMENT = 'CanNotCleanupDocument';
    const UNKNOWN_DOCUMENT_FORMAT = 'UnknownDocumentFormat';
    const CAN_NOT_CROP = 'CanNotCrop';
    const CAN_NOT_ROTATE = 'CanNotRotate';
    const CAN_NOT_DETECT_COLOR = 'CanNotDetectColor';
    const CAN_NOT_CONVERT_COLOR_DEPTH = 'CanNotConvertColorDepth';
    const PDF_CAN_NOT_ADD_FONT = 'PdfCanNotAddFont';
    const ACTION_EXECUTION_REJECTED = 'ActionExecutionRejected';
    const CAN_NOT_EXTRACT_TEXT = 'CanNotExtractText';
    const CAN_NOT_DETECT_BLANK_PAGES = 'CanNotDetectBlankPages';
    const CAN_NOT_MICR = 'CanNotMICR';
    const CAN_NOT_DETECT_PAGE_ORIENTATION = 'CanNotDetectPageOrientation';
    const CAN_NOT_DELETE_PAGE = 'CanNotDeletePage';
    const CAN_NOT_SAVE_AS_PDF = 'CanNotSaveAsPDF';
    const CAN_NOT_EXTRACT_IMAGE = 'CanNotExtractImage';
    const CAN_NOT_CLONE_IMAGE_REGION = 'CanNotCloneImageRegion';
    const CAN_NOT_REORDER_PAGES = 'CanNotReorderPages';
    const CAN_NOT_AUTO_CROP = 'CanNotAutoCrop';
    const CAN_NOT_SCALE_PAGE = 'CanNotScalePage';
    const CAN_NOT_MERGE_PAGES = 'CanNotMergePages';
    const CAN_NOT_GET_META_DATA = 'CanNotGetMetaData';
    const CAN_NOT_SET_METADATA = 'CanNotSetMetadata';
    const CAN_NOT_REMOVE_TEXT = 'CanNotRemoveText';
    const CAN_NOT_DOWNLOAD_DOCUMENT = 'CanNotDownloadDocument';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OK,
            self::ACTION_TIMED_OUT,
            self::EMPTY_PARAMETER,
            self::INVALID_API_KEY,
            self::NOT_ENOUGH_TOKENS,
            self::GENERIC_ERROR,
            self::INVALID_PARAMETER,
            self::INVALID_COLOR,
            self::OUT_OF_MEMORY,
            self::NOT_IMPLEMENTED,
            self::FILE_NOT_FOUND,
            self::ACCESS_DENIED,
            self::CAN_NOT_IMPORT_FILE_TO_PDF,
            self::PDF_CAN_NOT_BE_DECRYPTED,
            self::PDF_OPERATION_NOT_ALLOWED,
            self::PDF_CAN_NOT_OPEN_FILE,
            self::PDF_CAN_NOT_SAVE_FILE,
            self::CAN_NOT_CREATE_FILE,
            self::NO_DOCUMENT_PROVIDED,
            self::CAN_NOT_REMOVE_PAGE,
            self::CAN_NOT_SWAP_PAGES,
            self::CAN_NOT_MOVE_PAGE,
            self::CAN_NOT_ROTATE_PAGE,
            self::CAN_NOT_FLIP_PAGE,
            self::INVALID_PAGE_RANGE,
            self::CAN_NOT_REDUCE_PDF,
            self::CAN_NOT_AUTO_DESKEW,
            self::CAN_NOT_SPLIT,
            self::CAN_NOT_SAVE_AS_JPEG,
            self::CAN_NOT_DIGI_SIGN,
            self::CAN_NOT_PROTECT,
            self::CAN_NOT_CONVERT_TO_PDFA,
            self::CAN_NOT_ANNOTATE,
            self::CAN_NOT_CLEAR_PAGE,
            self::CAN_NOT_MERGE,
            self::CAN_NOT_GET_PAGE_THUMBNAIL,
            self::CAN_NOT_GET_DOCUMENT_PREVIEW,
            self::CAN_NOT_REMOVE_PAGE_FORM_FIELDS,
            self::CAN_NOT_INSERT_IMAGE,
            self::CAN_NOT_DRAW_IMAGE,
            self::CAN_NOT_INSERT_PAGE_NUMBER,
            self::CAN_NOT_INSERT_TEXT,
            self::CAN_NOT_READ_BARCODE,
            self::CAN_NOT_FLATTEN,
            self::CAN_NOT_EXPORT_MORE_THAN2_GIGABYTE_FILE,
            self::CAN_NOT_OPEN_SESSION,
            self::UNKNOWN_OR_EXPIRED_SESSION,
            self::CAN_NOT_SAVE_FILE,
            self::CAN_NOT_REPAIR_PDF,
            self::UNSUPPORTED_IMAGE_FORMAT,
            self::CAN_NOT_OCR,
            self::CAN_NOT_OPEN_IMAGE,
            self::CAN_NOT_SAVE_AS_PNG,
            self::CAN_NOT_SAVE_AS_TIFF,
            self::CAN_NOT_SAVE_AS_TIFF_MULTIPAGE,
            self::CAN_NOT_SET_INFO,
            self::CAN_NOT_SET_PAGE_BOX,
            self::CAN_NOT_EXTRACT_PAGE,
            self::CAN_NOT_INSERT_NEW_PAGE,
            self::CAN_NOT_CLONE_PAGE,
            self::CAN_NOT_SET_INITIAL_VIEW,
            self::CAN_NOT_ADJUST,
            self::CAN_NOT_RESIZE,
            self::CAN_NOT_FILTER,
            self::CAN_NOT_CLEANUP_DOCUMENT,
            self::UNKNOWN_DOCUMENT_FORMAT,
            self::CAN_NOT_CROP,
            self::CAN_NOT_ROTATE,
            self::CAN_NOT_DETECT_COLOR,
            self::CAN_NOT_CONVERT_COLOR_DEPTH,
            self::PDF_CAN_NOT_ADD_FONT,
            self::ACTION_EXECUTION_REJECTED,
            self::CAN_NOT_EXTRACT_TEXT,
            self::CAN_NOT_DETECT_BLANK_PAGES,
            self::CAN_NOT_MICR,
            self::CAN_NOT_DETECT_PAGE_ORIENTATION,
            self::CAN_NOT_DELETE_PAGE,
            self::CAN_NOT_SAVE_AS_PDF,
            self::CAN_NOT_EXTRACT_IMAGE,
            self::CAN_NOT_CLONE_IMAGE_REGION,
            self::CAN_NOT_REORDER_PAGES,
            self::CAN_NOT_AUTO_CROP,
            self::CAN_NOT_SCALE_PAGE,
            self::CAN_NOT_MERGE_PAGES,
            self::CAN_NOT_GET_META_DATA,
            self::CAN_NOT_SET_METADATA,
            self::CAN_NOT_REMOVE_TEXT,
            self::CAN_NOT_DOWNLOAD_DOCUMENT,
        ];
    }
}


