<?php
/**
 * PdfConformance
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PdfConformance Class Doc Comment
 *
 * @category Class
 * @description Specifies PDF versions and conformance levels of a PDF document.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PdfConformance
{
    /**
     * Possible values of this enum
     */
    const UNKNOWN = 'Unknown';
    const PDF10 = 'PDF10';
    const PDF11 = 'PDF11';
    const PDF12 = 'PDF12';
    const PDF13 = 'PDF13';
    const PDF14 = 'PDF14';
    const PDF15 = 'PDF15';
    const PDF16 = 'PDF16';
    const PDF17 = 'PDF17';
    const PDF20 = 'PDF20';
    const PDFA1A = 'PDFA1a';
    const PDFA1B = 'PDFA1b';
    const PDFA2A = 'PDFA2a';
    const PDFA2U = 'PDFA2u';
    const PDFA2B = 'PDFA2b';
    const PDFA3A = 'PDFA3a';
    const PDFA3U = 'PDFA3u';
    const PDFA3B = 'PDFA3b';
    const PDFUA1 = 'PDFUA1';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::PDF10,
            self::PDF11,
            self::PDF12,
            self::PDF13,
            self::PDF14,
            self::PDF15,
            self::PDF16,
            self::PDF17,
            self::PDF20,
            self::PDFA1A,
            self::PDFA1B,
            self::PDFA2A,
            self::PDFA2U,
            self::PDFA2B,
            self::PDFA3A,
            self::PDFA3U,
            self::PDFA3B,
            self::PDFUA1,
        ];
    }
}


