<?php
/**
 * SignatureHash
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * SignatureHash Class Doc Comment
 *
 * @category Class
 * @description Specifies the SHA (hash) algorithm to use while signing.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SignatureHash
{
    /**
     * Possible values of this enum
     */
    const SHA1 = 'SHA1';
    const SHA256 = 'SHA256';
    const SHA512 = 'SHA512';
    const SHA224 = 'SHA224';
    const SHA384 = 'SHA384';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SHA1,
            self::SHA256,
            self::SHA512,
            self::SHA224,
            self::SHA384,
        ];
    }
}


