<?php
/**
 * StandardFontName
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * StandardFontName Class Doc Comment
 *
 * @category Class
 * @description Defines the different available standard fonts (Standard Type 1) which can be used without prior definition.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StandardFontName
{
    /**
     * Possible values of this enum
     */
    const COURIER = 'Courier';
    const HELVETICA = 'Helvetica';
    const TIMES = 'Times';
    const SYMBOL = 'Symbol';
    const ZAPF_DINGBATS = 'ZapfDingbats';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::COURIER,
            self::HELVETICA,
            self::TIMES,
            self::SYMBOL,
            self::ZAPF_DINGBATS,
        ];
    }
}


