<?php
/**
 * BarcodeInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * BarcodeInfoTest Class Doc Comment
 *
 * @category    Class
 * @description Represents information about a read barcode.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BarcodeInfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BarcodeInfo"
     */
    public function testBarcodeInfo()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "barcode1_d_symbology"
     */
    public function testPropertyBarcode1DSymbology()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }

    /**
     * Test attribute "x1"
     */
    public function testPropertyX1()
    {
    }

    /**
     * Test attribute "x2"
     */
    public function testPropertyX2()
    {
    }

    /**
     * Test attribute "x3"
     */
    public function testPropertyX3()
    {
    }

    /**
     * Test attribute "x4"
     */
    public function testPropertyX4()
    {
    }

    /**
     * Test attribute "y1"
     */
    public function testPropertyY1()
    {
    }

    /**
     * Test attribute "y2"
     */
    public function testPropertyY2()
    {
    }

    /**
     * Test attribute "y3"
     */
    public function testPropertyY3()
    {
    }

    /**
     * Test attribute "y4"
     */
    public function testPropertyY4()
    {
    }

    /**
     * Test attribute "bbox_left_inches"
     */
    public function testPropertyBboxLeftInches()
    {
    }

    /**
     * Test attribute "bbox_top_inches"
     */
    public function testPropertyBboxTopInches()
    {
    }

    /**
     * Test attribute "bbox_width_inches"
     */
    public function testPropertyBboxWidthInches()
    {
    }

    /**
     * Test attribute "bbox_height_inches"
     */
    public function testPropertyBboxHeightInches()
    {
    }

    /**
     * Test attribute "page_number"
     */
    public function testPropertyPageNumber()
    {
    }

    /**
     * Test attribute "page_pixel_width"
     */
    public function testPropertyPagePixelWidth()
    {
    }

    /**
     * Test attribute "page_pixel_height"
     */
    public function testPropertyPagePixelHeight()
    {
    }

    /**
     * Test attribute "page_horizontal_resolution"
     */
    public function testPropertyPageHorizontalResolution()
    {
    }

    /**
     * Test attribute "page_vertical_resolution"
     */
    public function testPropertyPageVerticalResolution()
    {
    }
}
