<?php
/**
 * DrawableContentLayoutParametersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * DrawableContentLayoutParametersTest Class Doc Comment
 *
 * @category    Class
 * @description Represents information about the layout of a content, on the page it is drawn onto.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DrawableContentLayoutParametersTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DrawableContentLayoutParameters"
     */
    public function testDrawableContentLayoutParameters()
    {
    }

    /**
     * Test attribute "horizontal_position"
     */
    public function testPropertyHorizontalPosition()
    {
    }

    /**
     * Test attribute "vertical_position"
     */
    public function testPropertyVerticalPosition()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }

    /**
     * Test attribute "indent_from_edges"
     */
    public function testPropertyIndentFromEdges()
    {
    }

    /**
     * Test attribute "absolute_position_left"
     */
    public function testPropertyAbsolutePositionLeft()
    {
    }

    /**
     * Test attribute "absolute_position_top"
     */
    public function testPropertyAbsolutePositionTop()
    {
    }

    /**
     * Test attribute "absolute_width"
     */
    public function testPropertyAbsoluteWidth()
    {
    }

    /**
     * Test attribute "absolute_height"
     */
    public function testPropertyAbsoluteHeight()
    {
    }
}
