<?php
/**
 * ImageSaveAsPDFMRCParametersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ImageSaveAsPDFMRCParametersTest Class Doc Comment
 *
 * @category    Class
 * @description Represents the parameters for a save as PDF MRC action.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ImageSaveAsPDFMRCParametersTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ImageSaveAsPDFMRCParameters"
     */
    public function testImageSaveAsPDFMRCParameters()
    {
    }

    /**
     * Test attribute "file_id"
     */
    public function testPropertyFileId()
    {
    }

    /**
     * Test attribute "page_range"
     */
    public function testPropertyPageRange()
    {
    }

    /**
     * Test attribute "conformance"
     */
    public function testPropertyConformance()
    {
    }

    /**
     * Test attribute "color_image_compression"
     */
    public function testPropertyColorImageCompression()
    {
    }

    /**
     * Test attribute "bitonal_image_compression"
     */
    public function testPropertyBitonalImageCompression()
    {
    }

    /**
     * Test attribute "image_quality"
     */
    public function testPropertyImageQuality()
    {
    }

    /**
     * Test attribute "downscale_resolution"
     */
    public function testPropertyDownscaleResolution()
    {
    }

    /**
     * Test attribute "preserve_smoothing"
     */
    public function testPropertyPreserveSmoothing()
    {
    }

    /**
     * Test attribute "fast_web_view"
     */
    public function testPropertyFastWebView()
    {
    }

    /**
     * Test attribute "jbig2_pms_threshold"
     */
    public function testPropertyJbig2PmsThreshold()
    {
    }
}
