<?php
/**
 * PdfSetInitialViewParametersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * PdfSetInitialViewParametersTest Class Doc Comment
 *
 * @category    Class
 * @description Represents the parameters for a set initial view action.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PdfSetInitialViewParametersTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PdfSetInitialViewParameters"
     */
    public function testPdfSetInitialViewParameters()
    {
    }

    /**
     * Test attribute "file_id"
     */
    public function testPropertyFileId()
    {
    }

    /**
     * Test attribute "page_mode"
     */
    public function testPropertyPageMode()
    {
    }

    /**
     * Test attribute "layout_mode"
     */
    public function testPropertyLayoutMode()
    {
    }

    /**
     * Test attribute "non_full_screen_page_mode"
     */
    public function testPropertyNonFullScreenPageMode()
    {
    }

    /**
     * Test attribute "open_page"
     */
    public function testPropertyOpenPage()
    {
    }

    /**
     * Test attribute "open_zoom"
     */
    public function testPropertyOpenZoom()
    {
    }

    /**
     * Test attribute "hide_toolbar"
     */
    public function testPropertyHideToolbar()
    {
    }

    /**
     * Test attribute "hide_menubar"
     */
    public function testPropertyHideMenubar()
    {
    }

    /**
     * Test attribute "hide_window_ui"
     */
    public function testPropertyHideWindowUi()
    {
    }

    /**
     * Test attribute "fit_window"
     */
    public function testPropertyFitWindow()
    {
    }

    /**
     * Test attribute "center_window"
     */
    public function testPropertyCenterWindow()
    {
    }

    /**
     * Test attribute "display_doc_title"
     */
    public function testPropertyDisplayDocTitle()
    {
    }
}
