<?php
/**
 * ReduceWarningInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PassportPDF API
 *
 * Another brick in the cloud
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ReduceWarningInfoTest Class Doc Comment
 *
 * @category    Class
 * @description Represents information about a warning that occured during a reduce action.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ReduceWarningInfoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ReduceWarningInfo"
     */
    public function testReduceWarningInfo()
    {
    }

    /**
     * Test attribute "warning_code"
     */
    public function testPropertyWarningCode()
    {
    }

    /**
     * Test attribute "page_number"
     */
    public function testPropertyPageNumber()
    {
    }

    /**
     * Test attribute "page_image_number"
     */
    public function testPropertyPageImageNumber()
    {
    }

    /**
     * Test attribute "ext_warning_message"
     */
    public function testPropertyExtWarningMessage()
    {
    }
}
